# Generated by Django 6.0.7 on 2026-08-03 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cinemas',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='StatusMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Movie Statuses',
                'db_table': 'status_movie',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='ROLE_USER', max_length=50, null=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=True, null=True)),
                ('number_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('movie_format', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('poster', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='movies', to='CinemaBook.category')),
                ('status_movie', models.ForeignKey(blank=True, db_column='status_movie_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='CinemaBook.statusmovie')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cinema', models.ForeignKey(db_column='cinema_id', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='CinemaBook.cinema')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='CinemaBook.status')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='CinemaBook.room')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='CinemaBook.movie')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='CinemaBook.room')),
            ],
            options={
                'db_table': 'showtimes',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, default='CASH', max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, default='PENDING', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('showtime', models.ForeignKey(db_column='showtime_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='CinemaBook.showtime')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='CinemaBook.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='CinemaBook.booking')),
                ('seat', models.ForeignKey(db_column='seat_id', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='CinemaBook.seat')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='SeatShowtimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('lock_time', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(db_column='seat_id', on_delete=django.db.models.deletion.CASCADE, related_name='showtime_statuses', to='CinemaBook.seat')),
                ('showtime', models.ForeignKey(db_column='showtime_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='CinemaBook.showtime')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_seats', to='CinemaBook.user')),
            ],
            options={
                'db_table': 'seat_showtime_status',
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
