# Generated by Django 6.0.7 on 2026-08-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
