# Generated by Django 6.0.7 on 2026-08-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'type_tickets',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_ticket',
            field=models.ForeignKey(blank=True, db_column='type_ticket_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='CinemaBook.typeticket'),
        ),
    ]
