# Generated by Django 6.0.7 on 2026-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0004_typeticket_alter_ticket_price_ticket_type_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Admin'), ('ROLE_USER', 'User'), ('ROLE_STAFF', 'Staff')], default='ROLE_USER', max_length=50),
        ),
    ]
