# Generated by Django 6.0.7 on 2026-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('ZALO_PAY', 'Zalo Pay'), ('MOMO', 'MoMo')], default='CASH', max_length=50),
        ),
    ]
