# Generated by Django 6.0.7 on 2026-08-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0006_movie_actor_alter_booking_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'movie_formats',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_format',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='format',
            field=models.ForeignKey(blank=True, db_column='format_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='CinemaBook.movieformat'),
        ),
    ]
