# Generated by Django 6.0.7 on 2026-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0007_movieformat_remove_movie_movie_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='drirector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
