# Generated by Django 6.0.7 on 2026-08-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0010_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cinema',
            field=models.ForeignKey(blank=True, db_column='cinema_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='CinemaBook.cinema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Admin'), ('ROLE_CINEMA_MANAGER', 'Cinema Manager'), ('ROLE_USER', 'User'), ('ROLE_STAFF', 'Staff')], default='ROLE_USER', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('room', 'seat_number')},
        ),
    ]
