# Generated by Django 6.0.7 on 2026-08-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0011_user_cinema_alter_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seatshowtimestatus',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ROLE_ADMIN', 'Quản trị viên (Admin)'), ('ROLE_CINEMA_MANAGER', 'Quản lý Rạp (Cinema Manager)'), ('ROLE_USER', 'Khách hàng (User)'), ('ROLE_STAFF', 'Nhân viên (Staff)')], default='ROLE_USER', max_length=50, verbose_name='Vai trò (Role)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('number_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh đại diện (URL)')),
                ('cinema', models.ForeignKey(blank=True, db_column='cinema_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='CinemaBook.cinema', verbose_name='Rạp quản lý')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản hệ thống')),
            ],
            options={
                'verbose_name': 'Thông tin mở rộng',
                'verbose_name_plural': 'Danh sách Thông tin mở rộng',
                'db_table': 'user_profiles',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
