# Generated by Django 6.0.7 on 2026-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0012_alter_booking_user_alter_seatshowtimestatus_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number_phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
