# Generated by Django 6.0.7 on 2026-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0013_remove_userprofile_number_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
    ]
