# Generated by Django 6.0.7 on 2026-08-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0014_userprofile_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cinema',
            field=models.ForeignKey(blank=True, db_column='cinema_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='CinemaBook.cinema', verbose_name='Rạp / Chi nhánh phụ trách'),
        ),
    ]
