# Generated by Django 6.0.7 on 2026-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0015_alter_userprofile_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
