# Generated by Django 6.0.7 on 2026-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBook', '0016_ticket_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Đã soát vé'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian soát vé'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã vé'),
        ),
    ]
